# Gitee Go Release 流水线配置
# 当推送版本标签时触发

name: create-release
displayName: '创建 Release'

triggers:
  tag:
    include:
      - 'v*'

stages:
  - name: Release
    displayName: '发布阶段'
    steps:
      - name: Create Release
        displayName: '创建 Gitee Release'
        script: |
          echo "创建 Release..."
          # 获取标签版本号
          TAG_NAME=${CI_COMMIT_TAG:-$(git describe --tags --exact-match HEAD)}
          echo "标签版本: $TAG_NAME"
          
          # 这里需要调用 Gitee API 创建 Release
          # 需要使用 GITEE_TOKEN 环境变量
          echo "注意：需要在 Gitee Go 中配置 GITEE_TOKEN 变量"
          echo "Release 创建步骤需要根据 Gitee Go 的实际能力调整"

