# Gitee Go 流水线配置 - Android 构建
# Gitee Go 可能只支持 Linux runner，所以先配置 Android 构建

name: Build Android Server

triggers:
  push:
    branches:
      include:
        - main
        - master
        - develop
  tag:
    include:
      - 'v*'

stages:
  - stage:
      name: Build Android APK
      steps:
        - step: shell@1
          name: Setup Environment
          inputs:
            script: |
              echo "设置构建环境..."
              # 安装 Java
              sudo apt-get update
              sudo apt-get install -y openjdk-17-jdk
              # 安装 Flutter
              # 注意：需要根据 Gitee Go 的实际环境调整
              echo "环境设置完成"
        
        - step: shell@1
          name: Build APK
          inputs:
            script: |
              echo "开始构建 Android APK..."
              cd server
              # 安装依赖
              flutter pub get
              # 构建 APK
              flutter build apk --release
              echo "构建完成"

